# Generated by Django 5.0.4 on 2024-04-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.category')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discription', models.TextField()),
                ('date', models.DateField()),
                ('year', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.category')),
                ('name_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.marka')),
                ('name_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.model')),
            ],
        ),
    ]
