# Generated by Django 5.0.4 on 2024-04-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name_marka',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='marka',
            old_name='marka_name',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_name',
            new_name='model',
        ),
    ]
