# Generated by Django 5.0.4 on 2024-04-29 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_rename_name_category_car_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='marka',
            new_name='marka_name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='marka',
            name='marka',
        ),
        migrations.AddField(
            model_name='marka',
            name='marka_name',
            field=models.CharField(default=datetime.datetime(2024, 4, 29, 2, 57, 46, 140140, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
