# Generated by Django 5.0.4 on 2024-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_rename_marka_model_marka_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
