# Generated by Django 5.0.4 on 2024-04-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_car_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_date',
            new_name='date',
        ),
    ]
