# Generated by Django 5.0.4 on 2024-04-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_rename_created_date_car_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
