# Generated by Django 5.0.4 on 2024-04-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_car_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date',
            new_name='created_date',
        ),
    ]
