# Generated by Django 5.0.4 on 2024-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_rename_date_car_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
