# Generated by Django 5.0.4 on 2024-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(),
        ),
    ]
