# Generated by Django 5.0.4 on 2024-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_car_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
