# Generated by Django 5.0.4 on 2024-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_alter_car_volume_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
